.\" [program name] [section] [date YYYY-MM-DD] [version] [empty]
.TH YOUTUBE\-DL\-GUI 1 "2020-07-23" "Version 1.0" ""

.SH NAME
youtube\-dl\-gui \- cross platform graphical user interface for youtube\-dl.

.SH SYNOPSIS
.B youtube\-dl\-gui

.SH DESCRIPTION
Youtube\-dl\-gui is a graphical frontend of the popular youtube\-dl
command\-line program. As such, it does not take any command\-line parameters.
You may configure the program through the graphical settings dialog, or the
configuration file.

.SH FILES
.\" .IP text indent_size (.IP = Indented Paragraph)
.IP "\fB$HOME/.config/youtube\-dlg/settings.json\fR" 4
Configuration file.
.\" .IP text indent_size (.IP = Indented Paragraph)
.IP "\fB$HOME/.config/youtube\-dlg/log\fR" 4
Log file.

.SH NOTES
FAQS: https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md
MAINTAINER: https://github.com/oleksis/youtube-dl-gui/blob/master/README.md

.SH SEE ALSO
.BR youtube-dl (1)
