.TH youtube\-dlg 1 "January 2018" youtube\-dlg "User Manual"

.SH NAME
.PP
youtube\-dlg \- Cross platform Graphical User Interface for youtube-dl


.SH SYNOPSIS
.PP
youtube\-dlg 


.SH Description
.PP
youtube-dlg is a graphical frontend for the youtube-dl command-line program. As
  such, it does not take any command-line parameters. You may configure the
  program through the graphical settings dialog, or the configuration file.

.SH FILES
  \fI~/.config/youtube-dlg/settings.json\fR: youtube-dlg configuration file.
.br
  \fI/usr/share/doc/youtube-dlg/\fR: youtube-dlg documentation.

.SH SEE ALSO
.Xr youtube-dl 1 .
.PP
\fIhttps://github.com/MrS0m30n3/youtube-dl-gui/\fR
