name: Tests
on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: windows-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8.3
      uses: actions/setup-python@v2
      with:
          python-version: '3.8.3'
          architecture: 'x64'
    - name: Configure pip caching
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Build Translations
      run: python setup.py build_trans
    - name: Tests
      run: |-
        python -m unittest discover -s tests -v
